[project]
name = "AetherFlow"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "hujunjie", email = "hushengnian@example.com"},
]
dependencies = ["dependency-injector>=4.48.1", "pydantic>=2.11.7"]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
