name: Continuous Integration

# 在推送和拉取请求时触发
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - uses: actions/checkout@v4

    # 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 安装PDM
    - name: Install PDM
      run: pip install pdm

    # 安装依赖
    - name: Install dependencies
      run: pdm install --dev

    # 运行测试
    - name: Run tests
      run: pdm run pytest tests/ --verbose

    # 运行测试并生成覆盖率报告
    - name: Run tests with coverage
      run: |
        pdm run pip install pytest-cov
        pdm run pytest tests/ --cov=src/aetherflow --cov-report=term-missing

    # 检查代码质量
    - name: Check code quality
      run: |
        pdm run pip install flake8
        pdm run flake8 src/ --max-line-length=127
      continue-on-error: true
