name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pdm install --dev

      - name: Run tests
        run: |
          pdm run pytest

      - name: Build package
        run: |
          pdm build

      - name: Get tag name
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Check if Release exists
        id: check_release
        run: |
          if gh release view ${{ steps.tag.outputs.tag_name }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release if not exists
        if: steps.check_release.outputs.exists == 'false'
        run: |
          gh release create ${{ steps.tag.outputs.tag_name }} \
            --title "Release ${{ steps.tag.outputs.tag_name }}" \
            --notes "Automated release for ${{ steps.tag.outputs.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload wheel and sdist to Release
        run: |
          gh release upload ${{ steps.tag.outputs.tag_name }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
