name: Tag Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pdm install --dev

      - name: Run tests
        run: |
          pdm run pytest

      - name: Build package
        run: |
          pdm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 30
